const intermediateSentences = [
  "Typing quickly requires consistent practice and patience",
  "React makes it easier to create beautiful UIs",
  "JavaScript supports both functional and object-oriented styles",
  "Typing every day helps increase your words per minute",
  "Good posture improves your typing performance",
  "Always aim for accuracy before speed",
  "Typing with both hands is faster and better",
  "React components can be functional or class-based",
  "DOM manipulation is easier with libraries like React",
  "The JavaScript ecosystem grows rapidly",
  "CSS helps make websites look beautiful",
  "APIs connect the frontend with backend systems",
  "Practice typing paragraphs to gain real speed",
  "Typing is a great skill for developers and writers",
  "Make sure your hands are relaxed when typing",
  "Most developers type thousands of words daily",
  "Always refactor messy code for clarity",
  "Typing improves not just speed, but focus too",
  "React has a strong community and great tools",
  "Coding requires attention to detail",
  "Web apps are built with HTML, CSS, and JS",
  "Every developer benefits from fast typing",
  "Stay focused and avoid distractions",
  "Typing with rhythm helps with consistency",
  "Avoid looking at the keyboard too often",
  "Keyboard shortcuts make coding faster",
  "React uses a virtual DOM for performance",
  "Developers must test their applications",
  "Typing practice boosts productivity",
  "Learn to type without backspacing much",
  "Frontend frameworks improve development speed",
  "Keyboard layout familiarity boosts accuracy",
  "Keep your fingers on the home row",
  "Use tools like GitHub for collaboration",
  "Practice improves not just typing, but thinking",
  "Learn keyboard shortcuts for your IDE",
  "Typing races are a fun way to practice",
  "React uses JSX to mix HTML with JS",
  "Stay curious and keep learning",
  "Practice typing code snippets too",
];

export default intermediateSentences;
