const beginnerSentences = [
  "Hello world",
  "I love typing",
  "React is fun",
  "The sky is blue",
  "I am learning code",
  "She likes pizza",
  "We play outside",
  "They are friends",
  "He is smart",
  "It is raining",
  "I like to run",
  "Open the door",
  "Shut the window",
  "Time is gold",
  "Books are great",
  "Coding is cool",
  "Let’s start now",
  "Type this fast",
  "I can do it",
  "Keep moving on",
  "This is easy",
  "Try again",
  "Never give up",
  "Stay focused",
  "I like apples",
  "My name is John",
  "She is kind",
  "Dogs are cute",
  "Cats love milk",
  "Birds can fly",
  "This is a pen",
  "He runs fast",
  "I need water",
  "Read the book",
  "Watch the stars",
  "We love games",
  "I am strong",
  "Keep it up",
  "Look at that",
  "Do your best",
];

export default beginnerSentences;
